trigger:
- production  # Puedes cambiar esto según la rama que desees utilizar

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - script: |
      echo 'Instalando Node.js'
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
      
      echo 'Instalando npm'
      sudo apt-get install -y npm
      
      echo 'Instalando dependencias'
      npm install
    displayName: 'Instalar dependencias'

  - script: |
      echo 'Compilando la aplicación'
    displayName: 'Compilar'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Unit Tests'
    condition: succeededOrFailed()  # Publica los resultados de las pruebas aunque la compilación falle

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publicar artefactos'
